language: scala
scala:
  - 2.13.3
jdk:
  - oraclejdk11
before_install:
  - git fetch origin --tags
  - git tags
stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    - name: test
      script: sbt test
    - stage: release
      script: sbt ci-release
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt