language: scala
scala:
  - 2.13.3
jdk:
  - oraclejdk11
before_install:
  - git fetch origin --tags
stages:
  - name: test
    if: tag IS blank
  - name: release
    if: branch = master
jobs:
  include:
    - name: test
      script: sbt test
    - stage: release
      script: sbt 'release with-defaults'
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt