# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "25:c2:38:26:91:9f:34:76:db:ce:c6:d1:22:ca:b8:ce"
      - checkout
      - run: git fetch --tags


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
            - ~/.coursier
            - ~/.m2
            - ~/.cache
  
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: git config --global user.email "hello@scalawilliam.com"
      - run: git config --global user.name "ScalaWilliam"
      # run tests!
      - run: git status
      - run: cat /dev/null | sbt 'show version' 'release with-defaults'
